---------------------------------FUNCTIONS MICELLANIUS---------------------------------

SELECT CEIL(3.8);
------ROUND HIGH------
SELECT FLOOR(3.8);
------ROUND LOW---------
SELECT ROUND(3.5);
------ROUND WITH NUMBER OF DECIMALS-------
SELECT TRUNCATE(3.66666666,2);
------TRUNCATE THE NUMBER OF DECIMALS----
SELECT POWER(3,3);
-------...-----------
SELECT SQRT(9);
-----------...---------
SELECT RAND();
--------...----------
SELECT SIGN(-25);
-----------THE SIGN OF A NUMBER----------
SELECT ABS(-25);
-----------ABSOLUTE VALUE----------------
SELECT MOD(56,10);
--------MODULE---------------------
SELECT BIT_LENGTH("123456789");
-----------LENGTH IN BITS OF AN STRING----------
SELECT CHAR_LENGTH("123456789");
-------------LENGTH IN CHARS-------------
SELECT LENGTH("123456789");
----------LENGTH IN BYTES-------------
SELECT STRCMP("123","123");
----------IF THEY ARE EQUALS RETURN 0, IF THE FIRST STRING IS BEFORE IN THE ALPHABET ORDER RETURNS -1---
----------ELSE RETURNS 1-----------
SELECT REPEAT("123",100);
-----REPEAT THE STRING 100 TIMES-----------
SELECT LPAD("WE",5,"$");
--------IF THE STRING IS TOO SHORT THE THIRD PARAMETER FILL THIS THROUGHT THE LEFT SIDE-----
--------IF THE STRING IS TOO LONG THIS WILL BE CUT, THE SECOND PARAM IS THE LENGTH--------
SELECT RPAD("WE",10,"$");
--------SAME BEHAVIOR BUT FILLED BY THE RIGHT SIDE------------------
SELECT TRIM("  STRING  ");
SELECT TRIM(BOTH FROM "  STRING  ");
SELECT TRIM(LEADING FROM "  STRING  ");
SELECT TRIM(TRAILING FROM "  STRING  ");
--------DELETE THE REPETITIVE CHARACTER AT THE START AND AT THE END OF A STRING--
--WHATEVER IT IS IF WE USE THE BOTH OPTION, LEADING ONLY AT THE START, TRAILING AT THE END ONLY--
--BY DEFAULT BOTH IS SELECTED----------
SELECT SUBSTRING("123456789",3);
SELECT SUBSTRING("123456789" FROM 3 FOR 3);
SELECT SUBSTRING("123456789",3,3);
------STRING, START CHAR, LENGTH THE THIRD PARAM IS FACULTATIVE----------
SELECT POSITON("345" IN "123456789");
-------RETURNS THE POSITION OF THE FIRST CHARACTER OF THE FIRST ARGUMENT WHEN IT MATCH INTO THE SECOND-
SELECT LOCATE("345", "123456789");
-------THE SAME BUT IT ACCEPT AN EXTRA THIRD ARGUMENT WHO DEFINES THE START POSITION FOR SEARCH------
SELECT LOWER("ABC"); --LOWER CASE--
SELECT LCASE("ABD");
SELECT UPPER("abc"); --UPPER CASE--
SELECT UCASE("abc");

SELECT LEFT("123456789", 5);
SELECT RIGHT("123456789", 5);
---SUBSTRING LEFT OR RIGHT---
SELECT REVERSE("ABCDEF");
---------RETURNS "FEDCBA"-------
SELECT INSERT("123456789", 3, 5, "AA");
-------RETURNS "123AA9"--------

SELECT REPLACE("TEXTE", "EX", "OU");
----------RETURNS "TOUTE"-------------

SELECT CONCAT("123","456");
--------"123456"-------
SELECT CONCAT_WS("-","123","456");
----------"123-456"-----------
SELECT FIELD("OPTION2", "OPTION1", "OPTION2","OPTION3");
----RETURN THE NUMBER OF THE FIRST MATCH IS---
-----IN THIS CASE RETURNS 2--------
SELECT ASCII("T");
--------RETURNS ASCII CODE 82--------
SELECT CHAR("82", 82, 82.2);
--------RETURNS "TTT" BECAUSE THIS IS HIS ASCII CODE------
